// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.robot.subsystems;

import org.usfirst.frc2337.robot.Robot;
import org.usfirst.frc2337.robot.RobotMap;
import org.usfirst.frc2337.robot.commands.*;

import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *@author Bryce
 */
public class Auger extends Subsystem {

    private final CANTalon fuelDeGunker = RobotMap.fuelAgitatorfuelDeGunker;
    double currentSpeed = Robot.constants.kAuger_DefaultEnableSpeed;
    double incrementSpeed = Robot.constants.kAuger_IncrementSpeed;
    double reverseSpeed = Robot.constants.kAuger_DefaultReverseSpeed;
    public void initDefaultCommand() {
    	Robot.fuelAgitator.startFuelDeGunker(currentSpeed);
    	
    }
    
    public void startFuelDeGunker(double speed) {
    	fuelDeGunker.set(speed);
    }
    
    public void stopFuelDeGunker() {
    	fuelDeGunker.set(0);
    }
    public void reverseFuelDeGunker(double reverseSpeed){
    	
    }
    public void updateSpeed() {
		fuelDeGunker.set(currentSpeed);
		SmartDashboard.putNumber("Shooter Speed:", currentSpeed);
	}
	
	public void setAugerSpeed(double speed) {
		currentSpeed = speed;
		if(currentSpeed > 1.0) currentSpeed = 1;
		if(currentSpeed < 0.0) currentSpeed = 0;
		updateSpeed();
	}
	
	public void stopAuger() {
		fuelDeGunker.set(0);
	}
	
	public void incrementSpeed() {
		setAugerSpeed(currentSpeed += incrementSpeed);
	}
	
	public void decrementSpeed() {
		setAugerSpeed(currentSpeed -= incrementSpeed);
	}
    
    
   
}
