// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.robot.subsystems;

import org.usfirst.frc2337.robot.Robot;
import org.usfirst.frc2337.robot.RobotMap;
import org.usfirst.frc2337.robot.commands.*;

import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *@author Bryce
 */
public class FuelAgitator extends Subsystem {

    
    private final CANTalon fuelDeGunker = RobotMap.fuelAgitatorfuelDeGunker;
    double speed = Robot.constants.kFuelAgitator_DefaultEnableSpeed;
    double reverseSpeed = Robot.constants.kFuelAgitator_DefaultReverseSpeed;
    public void initDefaultCommand() {
    	Robot.fuelAgitator.startFuelDeGunker(speed);
    	
    }
    
    public void startFuelDeGunker(double speed) {
    	fuelDeGunker.set(speed);
    }
    
    public void stopFuelDeGunker() {
    	fuelDeGunker.set(0);
    }
    public void reverseFuelDeGunker(double reverseSpeed){
    	
    }
    
    
   
}
