// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.robot.subsystems;

import org.usfirst.frc2337.robot.Robot;
import org.usfirst.frc2337.robot.RobotMap;
import org.usfirst.frc2337.robot.commands.*;

import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * FUEL INTAKE - Picks the balls up off the floor
 */
public class FuelShooterLED extends Subsystem {
	private final Solenoid ledLeft = RobotMap.shooterRightLed;
	private final Solenoid ledRight = RobotMap.shooterLeftLed;
	private final Solenoid ledVision = RobotMap.visionLED;

    
    public void initDefaultCommand() {
       setDefaultCommand(new FuelShooterLED_main());
    }
    /**
     * Turn LEFT LED on/off
     * @param state true/false
     */
    public void rightLEDState(boolean state) {
    	ledLeft.set(state);
    }
    /**
     * Turn RIGHT LED on/off
     * @param state true/false
     */
    public void leftLEDState(boolean state) {
    	ledRight.set(state);
    }
    
    /**
     * Turn VISION LED on/off
     * @param state true/false
     */
    public void visionLEDState(boolean state) {
    	ledVision.set(state);
    }
}

