// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2337.robot.subsystems;

import org.usfirst.frc2337.robot.Robot;
import org.usfirst.frc2337.robot.RobotMap;
import org.usfirst.frc2337.robot.commands.*;

import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.Solenoid;

import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 *
 */
public class FuelIntakeArm extends Subsystem {


	private final DoubleSolenoid fuelIntakeArm = RobotMap.fuelIntakeArm_solenoid;

	public FuelIntakeArm() {

	}

	public void initDefaultCommand() {

	}


	public void extendIntakeArm() {
		fuelIntakeArm.set(DoubleSolenoid.Value.kForward);
	}
	
	public void retractIntakeArm() {
		fuelIntakeArm.set(DoubleSolenoid.Value.kReverse);
	}
	
	public void stopIntakeArm() {
		fuelIntakeArm.set(DoubleSolenoid.Value.kOff);
	}
	
}
