// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2337.robot.commands;
import org.usfirst.frc2337.robot.Robot;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class FuelIntakeArm_retract extends Command {
	
	double retractSpeed = Robot.constants.kFuelIntakeArm_RetractSpeed;
	double retractTime = Robot.constants.kFuelIntakeArm_RetractTime;
	double time = retractTime;

	public FuelIntakeArm_retract(double retractSpeed) {
	    	requires(Robot.fuelIntakeArm);
	    	this.retractSpeed = retractSpeed;
	    	
	}
    public FuelIntakeArm_retract() {

    requires(Robot.fuelIntakeArm);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.fuelIntakeArm.retractIntakeArm();

    	//Robot.fuelIntakeArm.retractIntakeArm(retractSpeed);
    	//setTimeout(time);
    	//Robot.fuelIntakeArm.stopIntakeArm();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return true;
    }

    // Called once after isFinished returns true
    protected void end() {
    
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    
    }
}
